#!/usr/bin/env python3
"""
Render all per-tenant config from tenants.yaml.

Onboarding a project = edit tenants.yaml, then `make render` (which runs this),
then `make reload`. This regenerates, atomically and consistently:

  docker/caddy/Caddyfile                       token -> tenant -> X-Scope-OrgID
  docker/mimir/overrides.yaml                  per-tenant metric retention/limits
  docker/loki/overrides.yaml                   per-tenant log retention
  docker/tempo/overrides.yaml                  per-tenant trace retention
  docker/grafana/bootstrap/*.ndjson            one pinned datasource set per org (API-applied)
  docker/grafana/provisioning/dashboards/dashboards.yaml   one provider per org
  scripts/.orgs                                org list for grafana-bootstrap.sh
  tenants.secrets.yaml                         per-tenant ingest token (generated, gitignored)
  tenants.lock.yaml                            per-tenant Grafana org_id (generated, gitignored — per instance)

Also regenerates one marked block, independent of tenants.yaml:

  docker/otel/collector-config.yaml (partial)  dropped resource attrs, from
                                                docker/otel/dropped-resource-attributes.yaml
                                                — applies to every signal, every
                                                tenant, at the collector. Add a
                                                name to that file, not this one.

You do NOT hand-assign org_id: this allocates a stable one per tenant into
tenants.lock.yaml and heals any bad input (missing / duplicate / reserved) to
the next free number instead of failing — same idea as the ingest-token ledger.

Keeping ONE source of truth is what makes "add a project" a one-line change
instead of a 6-file scavenger hunt that drifts out of sync.
"""
import json
import os
import secrets
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. Run `make render` (installs it) or "
             "`pip install pyyaml`.")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCKER = os.path.join(ROOT, "docker")
GEN = "# GENERATED by scripts/render.py from tenants.yaml — do not edit by hand.\n"
SECRETS_FILE = os.path.join(ROOT, "tenants.secrets.yaml")
LOCK_FILE = os.path.join(ROOT, "tenants.lock.yaml")


def load():
    path = os.path.join(ROOT, "tenants.yaml")
    if not os.path.exists(path):
        sys.exit("tenants.yaml not found — it's per-instance (gitignored). "
                 "Copy the template first:\n    cp tenants.example.yaml tenants.yaml")
    with open(path) as f:
        cfg = yaml.safe_load(f)
    defaults = cfg.get("defaults", {})
    tenants = cfg.get("tenants") or []       # tolerate an emptied list (last tenant deleted)
    reserved = cfg.get("reserved", []) or []

    # org_id is NO LONGER required or validated here — ensure_org_ids() allocates
    # a stable one per tenant and self-heals bad values. The id (the X-Scope-OrgID
    # data namespace) is the real key: it must be present and unique. display_name
    # must also be unique, because grafana-bootstrap.sh binds each org BY NAME.
    seen_ids, seen_names = set(), set()
    for t in tenants:
        if not t.get("id"):
            sys.exit(f"tenant {t.get('id', '?')} is missing required 'id'")
        if t["id"] in seen_ids:
            sys.exit(f"duplicate tenant id: {t['id']}")
        name = t.get("display_name", t["id"])
        if "\n" in name or "\r" in name:
            sys.exit(f"display_name for '{t['id']}' must be a single line — it's "
                     "written one-per-line to scripts/.orgs. (Quotes, |, etc. are fine.)")
        if name in seen_names:
            sys.exit(f"duplicate display_name '{name}' — org names must be unique "
                     "(grafana-bootstrap.sh resolves each org by name)")
        seen_ids.add(t["id"])
        seen_names.add(name)
        # fold defaults in
        for k, v in defaults.items():
            t.setdefault(k, v)

    # Reserved platform tenants (e.g. _infra): a token + limits like any tenant,
    # but no Grafana org of their own — read from the admin org (org 1). Their
    # id must start with "_" so they can never collide with a project id.
    for r in reserved:
        if not r.get("id"):
            sys.exit("reserved entry is missing required 'id'")
        if not r["id"].startswith("_"):
            sys.exit(f"reserved tenant id must start with '_': {r['id']}")
        if r["id"] in seen_ids:
            sys.exit(f"duplicate tenant id: {r['id']}")
        if r.get("org_id"):
            sys.exit(f"reserved tenant {r['id']} must not set org_id "
                     "(its data is read from the admin org, org 1)")
        seen_ids.add(r["id"])
        for k, v in defaults.items():
            r.setdefault(k, v)

    return tenants, reserved


def write(path, content):
    full = os.path.join(DOCKER, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w") as f:
        f.write(content)
    print(f"  wrote docker/{path}")


def ensure_tokens(tenants):
    """Attach each tenant's ingest token, generating any that are missing.

    Tokens live in tenants.secrets.yaml, kept separate from tenants.yaml so the
    project list never carries secrets (both are per-instance/gitignored anyway).
    Generation is idempotent: an existing token is reused forever — silently
    rotating it would 401 every app already exporting with it. Only tenants without
    a token get a fresh one. To rotate deliberately, delete that tenant's line in
    the secrets file and re-render.
    """
    store = {}
    if os.path.exists(SECRETS_FILE):
        with open(SECRETS_FILE) as f:
            store = yaml.safe_load(f) or {}

    generated = []
    for t in tenants:
        tok = store.get(t["id"])
        if not tok:
            tok = "ptk_" + secrets.token_urlsafe(32)
            store[t["id"]] = tok
            generated.append(t["id"])
        t["token"] = tok

    if generated:
        with open(SECRETS_FILE, "w") as f:
            f.write("# GENERATED + managed by scripts/render.py. GITIGNORED — treat as secrets.\n")
            f.write("# One ingest token per tenant id. Rotate = delete a line, then `make render`.\n")
            for tid in sorted(store):
                f.write(f'{tid}: "{store[tid]}"\n')
        os.chmod(SECRETS_FILE, 0o600)
        print(f"  generated token(s) for {', '.join(generated)} -> tenants.secrets.yaml:")
        for tid in generated:
            print(f"      {tid}: {store[tid]}")
    return generated


def ensure_org_ids(tenants):
    """Assign each project tenant a STABLE Grafana org_id, self-healing bad input.

    You should not have to hand-pick org_id. This allocates one per tenant into
    tenants.lock.yaml (gitignored, local to this deployment) and reuses it forever
    — same pattern as ensure_tokens. Rules, in order of authority:

      1. A number already recorded in the lock is kept — stable across renders.
      2. Otherwise an org_id written in tenants.yaml is honored as a HINT, but only
         if it's a valid, free number (>= 2, not already taken, not a tombstone).
      3. Anything invalid — missing, non-int, org 1, or colliding with a number
         already in use — is HEALED to the next free number >= 2. Render never
         aborts on a messed-up org_id; it just picks the next available and warns.

    A removed tenant's number stays in the lock as a tombstone: reserved forever,
    never reissued (Grafana never recycles org ids, so neither do we). The actual
    Grafana org is bound by NAME at bootstrap, so even if a number here drifts from
    what Grafana assigned, provisioning still resolves correctly.
    """
    ledger = {}
    if os.path.exists(LOCK_FILE):
        data = yaml.safe_load(open(LOCK_FILE)) or {}
        ledger = dict(data.get("allocations", {}))

    current = {t["id"] for t in tenants}
    # Numbers belonging to tenants no longer in tenants.yaml: keep as tombstones.
    tombstones = {tid: n for tid, n in ledger.items()
                  if tid not in current and isinstance(n, int)}
    used = {1} | set(tombstones.values())   # 1 = platform admin, always reserved

    def next_free():
        n = 2
        while n in used:
            n += 1
        return n

    healed, assigned = [], {}
    # Phase 1: every current tenant already in the lock keeps its number. Reserve
    # these FIRST — so adding/reordering a tenant can never steal an existing one's
    # number (allocation is order-independent for anyone already allocated).
    for t in tenants:
        tid = t["id"]
        n = ledger.get(tid)
        if isinstance(n, int) and n >= 2 and n not in used:
            assigned[tid] = n
            used.add(n)
    # Phase 2: tenants with no locked number yet — honor a valid yaml hint, else
    # heal to the next free number. (A corrupt lock with duplicate numbers lands
    # here for the loser and gets healed too.)
    for t in tenants:
        tid = t["id"]
        if tid in assigned:
            continue
        candidate = ledger.get(tid, t.get("org_id"))   # lock wins, else yaml hint
        if isinstance(candidate, int) and candidate >= 2 and candidate not in used:
            org_id = candidate
        else:
            org_id = next_free()
            if candidate is not None:
                healed.append((tid, candidate, org_id))
        used.add(org_id)
        assigned[tid] = org_id
    for t in tenants:
        t["org_id"] = assigned[t["id"]]

    new_ledger = {**tombstones, **assigned}
    with open(LOCK_FILE, "w") as f:
        f.write(GEN)
        f.write("# Per-instance local state — GITIGNORED, not shared. Each deployment has\n"
                "# its own Grafana with its own org ids, so these numbers are local to THIS\n"
                "# instance and need not match any other. Orgs are resolved by NAME at\n"
                "# bootstrap, so the number here is just a local label; if this file is lost\n"
                "# it simply re-allocates. While it survives, a number is never reused — a\n"
                "# removed tenant's number stays below as a reserved tombstone.\n")
        f.write("allocations:\n")
        for tid, n in sorted(new_ledger.items(), key=lambda kv: kv[1]):
            tag = "" if tid in current else "   # retired (reserved, not in tenants.yaml)"
            f.write(f"  {tid}: {n}{tag}\n")
    print("  wrote tenants.lock.yaml")
    for tid, req, got in healed:
        print(f"  ⚠ org_id: tenant '{tid}' wanted {req!r} but it was taken/invalid "
              f"-> healed to {got}.")
    return new_ledger


def render_caddy(tenants):
    blocks = []
    for t in tenants:
        tid = t["id"]
        blocks.append(
            f'\t@{tid} header Authorization "Bearer {t["token"]}"\n'
            f'\thandle @{tid} {{\n'
            f'\t\tlog_name ok                    # accepted -> sampled success sink\n'
            f'\t\treverse_proxy otel-collector:4318 {{\n'
            f'\t\t\theader_up X-Scope-OrgID {tid}\n'
            f'\t\t\theader_up -Authorization\n'
            f'\t\t}}\n'
            f'\t}}\n'
        )
    body = "\n".join(blocks)
    write("caddy/Caddyfile",
          GEN +
          # --- Global options: access-log routing into two sinks. ---------------
          # Alloy scrapes Caddy's stdout into the _infra tenant, so these lines show
          # up in Grafana. We split them so the edge log stays useful AND cheap:
          #   access_fail -> EVERY rejected request (401), never sampled = the signal
          #                  you actually want (a misconfigured token, a probe, etc.).
          #   access_ok   -> accepted requests, heavily sampled = a heartbeat proving
          #                  traffic flows, without logging every telemetry push.
          # The Authorization header (bearer token) is deleted from every line so
          # project tokens never land in Loki. 'default' keeps Caddy's own runtime
          # log on stderr and excludes the access namespaces (no dup / no unsampled
          # leak). Tune the success heartbeat via the sampling block below.
          "{\n"
          "\tadmin off\n"
          "\tauto_https off   # prod: remove + set email for auto-HTTPS\n\n"
          "\tlog default {\n"
          "\t\toutput stderr\n"
          "\t\texclude http.log.access.ok http.log.access.fail\n"
          "\t}\n"
          "\tlog access_fail {          # all rejections, unsampled\n"
          "\t\toutput stdout\n"
          "\t\tformat filter {\n"
          "\t\t\twrap json\n"
          "\t\t\trequest>headers>Authorization delete\n"
          "\t\t}\n"
          "\t\tinclude http.log.access.fail\n"
          "\t}\n"
          "\tlog access_ok {            # accepted requests, sampled heartbeat\n"
          "\t\toutput stdout\n"
          "\t\tformat filter {\n"
          "\t\t\twrap json\n"
          "\t\t\trequest>headers>Authorization delete\n"
          "\t\t}\n"
          "\t\tinclude http.log.access.ok\n"
          "\t\t# Throttle the accepted-request heartbeat: log the first few requests\n"
          "\t\t# in each sampling window, then drop the rest, so a busy edge doesn't\n"
          "\t\t# flood Loki with 200s. NOTE: no 'interval' on purpose — its Caddyfile\n"
          "\t\t# syntax changed between 2.10 (integer ns) and 2.11 (duration like 1m),\n"
          "\t\t# so hard-coding either breaks the other; omitting it uses the built-in\n"
          "\t\t# default and parses on both. Failures are never sampled (sink above).\n"
          "\t\tsampling {\n"
          "\t\t\tfirst 3\n"
          "\t\t\tthereafter 100000\n"
          "\t\t}\n"
          "\t}\n"
          "}\n\n"
          ":4318 {\n"
          "\tlog                        # enable access logging; log_name (below) routes each request to a sink\n\n"
          "\t# --- BEGIN tenants ---\n"
          f"{body}"
          "\t# --- END tenants ---\n\n"
          "\thandle {\n"
          "\t\tlog_name fail              # rejected -> unsampled failure sink\n"
          '\t\trespond "Unauthorized: missing or invalid project token" 401\n'
          "\t}\n}\n")


def render_mimir(tenants):
    lines = [GEN, "overrides:"]
    for t in tenants:
        lines += [
            f"  {t['id']}:",
            f"    compactor_blocks_retention_period: {t['metrics_retention']}",
            f"    ingestion_rate: {t['ingestion_rate']}",
            f"    max_global_series_per_user: {t['max_series']}",
        ]
    write("mimir/overrides.yaml", "\n".join(lines) + "\n")


def render_loki(tenants):
    lines = [GEN, "overrides:"]
    for t in tenants:
        lines += [f"  {t['id']}:", f"    retention_period: {t['logs_retention']}"]
    write("loki/overrides.yaml", "\n".join(lines) + "\n")


def render_tempo(tenants):
    # NOTE: Tempo per-tenant overrides REPLACE the defaults for that tenant
    # (they don't merge), so every limit the tenant needs must be restated here —
    # notably the ingestion rate (or spans are dropped at 0 bytes/s) AND the
    # metrics_generator processors (or span-metrics/service-graphs silently
    # turn OFF for that tenant — zero traces_spanmetrics_* in Mimir).
    lines = [GEN, "overrides:"]
    for t in tenants:
        lines += [
            f"  {t['id']}:",
            "    ingestion:",
            f"      rate_limit_bytes: {t['traces_rate_limit_bytes']}",
            f"      burst_size_bytes: {t['traces_burst_bytes']}",
            "    compaction:",
            f"      block_retention: {t['traces_retention']}",
            "    metrics_generator:",
            "      processors: [service-graphs, span-metrics, local-blocks]",
        ]
    write("tempo/overrides.yaml", "\n".join(lines) + "\n")


def render_datasources(tenants):
    # NOT file-provisioned: Grafana hard-fails at boot if a datasource/dashboard
    # provider names an org that doesn't exist yet, and orgs can only be created
    # after Grafana is up. So per-org datasources are created by the API-driven
    # grafana-bootstrap.sh AFTER the orgs exist. We emit one NDJSON file per
    # tenant (one datasource API payload per line — no jq needed in the script).
    for t in tenants:
        tid = t["id"]
        ds = [
            {"name": "Mimir", "uid": f"mimir-{tid}", "type": "prometheus",
             "access": "proxy", "url": "http://mimir:9009/prometheus",
             "isDefault": True,
             "jsonData": {"httpHeaderName1": "X-Scope-OrgID", "timeInterval": "1m"},
             "secureJsonData": {"httpHeaderValue1": tid}},
            {"name": "Loki", "uid": f"loki-{tid}", "type": "loki",
             "access": "proxy", "url": "http://loki:3100",
             "jsonData": {"httpHeaderName1": "X-Scope-OrgID",
                          "derivedFields": [{"datasourceUid": f"tempo-{tid}",
                                             "matcherType": "label",
                                             "matcherRegex": "trace_id",
                                             "name": "TraceID",
                                             "url": "${__value.raw}"}]},
             "secureJsonData": {"httpHeaderValue1": tid}},
            {"name": "Tempo", "uid": f"tempo-{tid}", "type": "tempo",
             "access": "proxy", "url": "http://tempo:3200",
             "jsonData": {"httpHeaderName1": "X-Scope-OrgID",
                          "tracesToLogsV2": {"datasourceUid": f"loki-{tid}"},
                          "nodeGraph": {"enabled": True}},
             "secureJsonData": {"httpHeaderValue1": tid}},
        ]
        write(f"grafana/bootstrap/{tid}.ndjson",
              "".join(json.dumps(d, separators=(",", ":")) + "\n" for d in ds))


def render_dashboards_provider(tenants):
    # Org 1 (platform/admin) only — see render_datasources for why per-org
    # providers can't be file-provisioned. Per-org dashboards (if any) are
    # imported by grafana-bootstrap.sh after the orgs exist.
    write("grafana/provisioning/dashboards/dashboards.yaml", GEN + """apiVersion: 1
providers:
  - name: 'admin-dashboards'
    orgId: 1
    type: file
    disableDeletion: true
    updateIntervalSeconds: 30
    allowUiUpdates: false
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true
""")


def render_orgs(tenants):
    # consumed by grafana-bootstrap.sh (org_id|id|display_name)
    path = os.path.join(ROOT, "scripts", ".orgs")
    with open(path, "w") as f:
        for t in tenants:
            f.write(f"{t['org_id']}|{t['id']}|{t.get('display_name', t['id'])}\n")
    print("  wrote scripts/.orgs")


COLLECTOR_ATTRS_BEGIN = "          # --- BEGIN GENERATED from docker/otel/dropped-resource-attributes.yaml — edit that file + `make render`, not this block ---\n"
COLLECTOR_ATTRS_END = "          # --- END GENERATED ---\n"


def render_collector_attrs():
    """Regenerate the marked delete_key block in collector-config.yaml from
    docker/otel/dropped-resource-attributes.yaml.

    Unlike the other render_* functions, collector-config.yaml is NOT
    per-instance data (no tenant tokens/ids in it — it's identical on every
    deployment) and is mostly hand-tuned (memory_limiter, batch, filter/logs
    rules). So it stays a committed file that's edited directly, except for
    this one marked block, which is regenerated in place rather than the
    whole file being rewritten from scratch like render_caddy() etc.
    """
    attrs_path = os.path.join(DOCKER, "otel", "dropped-resource-attributes.yaml")
    with open(attrs_path) as f:
        attrs = yaml.safe_load(f) or []
    if not isinstance(attrs, list) or not all(isinstance(a, str) and a for a in attrs):
        sys.exit("docker/otel/dropped-resource-attributes.yaml must be a YAML list of non-empty strings")
    if len(set(attrs)) != len(attrs):
        sys.exit("docker/otel/dropped-resource-attributes.yaml has a duplicate attribute name")

    config_path = os.path.join(DOCKER, "otel", "collector-config.yaml")
    with open(config_path) as f:
        text = f.read()

    try:
        before, rest = text.split(COLLECTOR_ATTRS_BEGIN, 1)
        _, after = rest.split(COLLECTOR_ATTRS_END, 1)
    except ValueError:
        sys.exit("collector-config.yaml: GENERATED markers not found or malformed — "
                 "did the surrounding block get edited by hand?")

    generated = "".join(f'          - delete_key(attributes, "{a}")\n' for a in attrs)
    with open(config_path, "w") as f:
        f.write(before + COLLECTOR_ATTRS_BEGIN + generated + COLLECTOR_ATTRS_END + after)
    print(f"  wrote docker/otel/collector-config.yaml ({len(attrs)} dropped resource attributes)")


def main():
    tenants, reserved = load()
    ingest = tenants + reserved   # everything that ingests: projects + reserved
    print(f"Rendering {len(tenants)} project tenant(s) + {len(reserved)} reserved:")
    ensure_tokens(ingest)          # tokens/caddy/limits apply to ALL ingest tenants
    ensure_org_ids(tenants)        # Grafana org_id: projects only (reserved use org 1)
    render_caddy(ingest)
    render_mimir(ingest)
    render_loki(ingest)
    render_tempo(ingest)
    render_datasources(tenants)    # per-org datasources: projects only
    render_dashboards_provider(tenants)
    render_orgs(tenants)           # Grafana orgs: projects only (reserved use org 1)
    render_collector_attrs()       # dropped-resource-attributes.yaml -> collector-config.yaml
    print("Done. Next: `make reload` (and `make bootstrap-orgs` on first run).")


if __name__ == "__main__":
    main()
